### ISSUE TITLE
Clean pitch tracking data + documentation

### ISSUE THREAD

**Issue by kwatcharasupat** [FBA-Janitor/MIG-MusicPerformanceAnalysis-Code#4]
See [here](https://github.com/FBA-Janitor/MIG-MusicPerformanceAnalysis-Code/blob/master/src/data_parse/README.md) for an overview. 

- Example config [file](https://github.com/FBA-Janitor/MIG-MusicPerformanceAnalysis-Code/blob/master/src/data_parse/config/assessment_scores/assessment_score_name_changes.yaml)
- Example automation [code](https://github.com/FBA-Janitor/MIG-MusicPerformanceAnalysis-Code/tree/master/src/data_parse/scripts/assessments_scores)

This issue is for 
- [ ] Creating reusable code (with config files) if needed to do the tasks below
- [ ] Creating symlinks for pyin features into https://github.com/FBA-Janitor/MIG-FBA-PitchTracking. See above link for folder structure.
- [ ] Documenting which data point has/has not been pitchtracked
- [ ] Document data format and code
